export const shortLongTextMock =
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In hendrerit gravida rutrum quisque non. Consectetur adipiscing elit duis tristique sollicitudin nibh sit.';

export const middleLongTextMock =
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In hendrerit gravida rutrum quisque non. Consectetur adipiscing elit duis tristique sollicitudin nibh sit. Proin sagittis nisl rhoncus mattis rhoncus. Leo in vitae turpis massa sed elementum tempus. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque. Sed elementum tempus egestas sed. Nunc congue nisi vitae suscipit tellus mauris. Tempus egestas sed sed risus pretium quam vulputate dignissim suspendisse. Arcu non odio euismod lacinia at quis risus. Sed vulputate odio ut enim. Libero enim sed faucibus turpis in. Amet nulla facilisi morbi tempus iaculis urna id volutpat. Pharetra et ultrices neque ornare aenean euismod elementum.';

export const longTextMock =
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pharetra massa massa ultricies mi quis hendrerit dolor magna eget. Vel pharetra vel turpis nunc eget lorem dolor. Rhoncus urna neque viverra justo nec ultrices. Tempus egestas sed sed risus pretium quam. Eu lobortis elementum nibh tellus molestie nunc non. Amet facilisis magna etiam tempor orci eu. Mi quis hendrerit dolor magna. Lacus vestibulum sed arcu non odio euismod. Id consectetur purus ut faucibus pulvinar. Porta non pulvinar neque laoreet suspendisse interdum consectetur libero id. Vitae tempus quam pellentesque nec nam aliquam sem. Vitae turpis massa sed elementum tempus egestas sed sed. Tincidunt lobortis feugiat vivamus at augue eget arcu dictum. Egestas integer eget aliquet nibh praesent tristique magna sit.\n' +
    '\n' +
    'Facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Ipsum dolor sit amet consectetur adipiscing. Non quam lacus suspendisse faucibus interdum posuere. Sed lectus vestibulum mattis ullamcorper. Nascetur ridiculus mus mauris vitae ultricies leo integer. Erat imperdiet sed euismod nisi porta lorem mollis aliquam. Enim praesent elementum facilisis leo. Nunc congue nisi vitae suscipit tellus mauris a. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Sit amet commodo nulla facilisi. Augue neque gravida in fermentum et. Accumsan lacus vel facilisis volutpat est velit egestas. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Viverra tellus in hac habitasse. Egestas diam in arcu cursus euismod quis viverra. Et pharetra pharetra massa massa ultricies mi quis. In ornare quam viverra orci.\n' +
    '\n' +
    'Ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Non curabitur gravida arcu ac tortor dignissim convallis aenean. Diam volutpat commodo sed egestas. Porttitor eget dolor morbi non arcu risus quis varius. Volutpat ac tincidunt vitae semper. Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Accumsan tortor posuere ac ut consequat semper. Tempor nec feugiat nisl pretium fusce id velit. Cursus eget nunc scelerisque viverra mauris in aliquam sem. Purus sit amet luctus venenatis lectus magna fringilla. Consequat id porta nibh venenatis. Sagittis eu volutpat odio facilisis mauris sit. Scelerisque fermentum dui faucibus in ornare quam viverra. Id faucibus nisl tincidunt eget. At urna condimentum mattis pellentesque id nibh. Dictumst quisque sagittis purus sit amet volutpat consequat mauris.\n' +
    '\n' +
    'Adipiscing elit duis tristique sollicitudin. Aliquam id diam maecenas ultricies mi eget mauris. At elementum eu facilisis sed odio morbi quis commodo. Eu scelerisque felis imperdiet proin fermentum. Elementum nibh tellus molestie nunc. Fermentum et sollicitudin ac orci phasellus. Fusce id velit ut tortor pretium viverra. Nulla pharetra diam sit amet nisl suscipit adipiscing bibendum est. Ac ut consequat semper viverra nam. Etiam erat velit scelerisque in dictum non.\n' +
    '\n' +
    'A pellentesque sit amet porttitor eget dolor. Lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant. Facilisi cras fermentum odio eu. Interdum velit euismod in pellentesque massa placerat. Pharetra convallis posuere morbi leo urna molestie at. Orci phasellus egestas tellus rutrum tellus pellentesque eu. Massa tempor nec feugiat nisl pretium fusce id velit. Vitae auctor eu augue ut lectus arcu bibendum at. Netus et malesuada fames ac turpis egestas. Etiam sit amet nisl purus in. Feugiat in fermentum posuere urna. Nibh cras pulvinar mattis nunc sed blandit libero volutpat. Ut diam quam nulla porttitor. Consequat mauris nunc congue nisi vitae suscipit. Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Sit amet tellus cras adipiscing enim eu turpis egestas pretium. Sapien pellentesque habitant morbi tristique senectus et netus et. Amet venenatis urna cursus eget. Quis risus sed vulputate odio ut enim.\n' +
    '\n' +
    'Vulputate odio ut enim blandit volutpat maecenas volutpat blandit. Est velit egestas dui id ornare arcu odio ut sem. Dolor sit amet consectetur adipiscing. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus et. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Amet mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Tellus at urna condimentum mattis pellentesque id nibh. Imperdiet massa tincidunt nunc pulvinar sapien. Lacus sed viverra tellus in hac habitasse platea dictumst vestibulum. Diam ut venenatis tellus in. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum sociis. Platea dictumst vestibulum rhoncus est pellentesque elit. Ut etiam sit amet nisl purus. Id leo in vitae turpis massa. Feugiat nibh sed pulvinar proin gravida hendrerit lectus. Vitae ultricies leo integer malesuada nunc vel risus commodo viverra. Nec feugiat in fermentum posuere urna nec tincidunt. Dictum non consectetur a erat nam.\n' +
    '\n' +
    'Cras semper auctor neque vitae tempus quam pellentesque. Nulla facilisi nullam vehicula ipsum. Odio tempor orci dapibus ultrices. Pellentesque elit eget gravida cum sociis. Velit egestas dui id ornare arcu odio. Eu nisl nunc mi ipsum faucibus. Aliquam ultrices sagittis orci a scelerisque purus. Id diam vel quam elementum pulvinar etiam. Posuere lorem ipsum dolor sit. At elementum eu facilisis sed odio morbi quis. Phasellus faucibus scelerisque eleifend donec. Nisi scelerisque eu ultrices vitae auctor eu augue ut lectus. Euismod in pellentesque massa placerat duis ultricies. Accumsan lacus vel facilisis volutpat est velit egestas dui. Fringilla ut morbi tincidunt augue interdum velit euismod in. Diam in arcu cursus euismod quis viverra nibh cras pulvinar. Urna et pharetra pharetra massa. Facilisis volutpat est velit egestas dui. Vestibulum lorem sed risus ultricies.\n' +
    '\n' +
    'Id neque aliquam vestibulum morbi blandit. Mattis vulputate enim nulla aliquet. Vel turpis nunc eget lorem dolor sed. Vulputate dignissim suspendisse in est ante in nibh. Pellentesque id nibh tortor id aliquet lectus proin. Odio aenean sed adipiscing diam donec adipiscing tristique. Malesuada fames ac turpis egestas maecenas. Pellentesque habitant morbi tristique senectus et netus et. Amet mattis vulputate enim nulla. In ante metus dictum at tempor commodo ullamcorper a. Lorem ipsum dolor sit amet consectetur adipiscing. Morbi tristique senectus et netus et. Elementum integer enim neque volutpat.\n' +
    '\n' +
    'Nunc scelerisque viverra mauris in aliquam sem fringilla ut. Est ullamcorper eget nulla facilisi etiam dignissim diam quis enim. Malesuada pellentesque elit eget gravida cum sociis natoque. Aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis. Urna cursus eget nunc scelerisque viverra. Morbi tristique senectus et netus et malesuada. Tristique nulla aliquet enim tortor at auctor. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Vulputate dignissim suspendisse in est ante in nibh. Augue lacus viverra vitae congue eu consequat. Mauris vitae ultricies leo integer. Felis eget nunc lobortis mattis aliquam. Consectetur libero id faucibus nisl tincidunt eget. Erat nam at lectus urna duis convallis convallis tellus id. Auctor neque vitae tempus quam pellentesque nec nam aliquam.\n' +
    '\n' +
    'Quis lectus nulla at volutpat diam ut venenatis tellus. Gravida rutrum quisque non tellus orci ac auctor. Nibh nisl condimentum id venenatis a. At elementum eu facilisis sed odio morbi quis. Praesent tristique magna sit amet purus. Ultrices neque ornare aenean euismod elementum nisi quis. Ornare arcu dui vivamus arcu felis bibendum ut. Viverra justo nec ultrices dui sapien eget mi. Quis commodo odio aenean sed adipiscing diam. Eu turpis egestas pretium aenean pharetra magna ac placerat vestibulum. Tristique magna sit amet purus gravida quis blandit. Turpis cursus in hac habitasse platea. Risus nec feugiat in fermentum posuere urna nec tincidunt praesent.';
